name: cmd

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build KorbitSideShiftCryptoConverter.Cmd/KorbitSideShiftCryptoConverter.Cmd.csproj --no-restore --configuration ${{ matrix.configuration }} --output ${{ matrix.configuration }}

    - name: Get release version from tag name
      if: startsWith(github.ref, 'refs/tags/')
      id: release-version
      uses: dawidd6/action-get-tag@v1
      with:
        # Strip `v` prefix
        strip_v: true

    - name: Set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        RELEASE_VERSION: ${{ steps.release-version.outputs.tag }}
        ZIP_RELEASE_FILENAME: KorbitSideShiftConverter-${{ steps.release-version.outputs.tag }}-${{ runner.os }}.zip
        ZIP_RELEASE_FILEPATH: ${{ matrix.configuration }}/KorbitSideShiftConverter-${{ steps.release-version.outputs.tag }}-${{ runner.os }}.zip

    - name: Zip Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: zip
        filename: ${{ env.ZIP_RELEASE_FILENAME }}
        directory: ${{ matrix.configuration }}
        exclusions: "*.pdb *.xml"

    - name: Automatic GH Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v0.1.14
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ${{ env.ZIP_RELEASE_FILEPATH }}
        name: Release ${{ env.RELEASE_VERSION }}
        generate_release_notes: true
